// Mocks generated by Mockito 5.4.6 from annotations
// in vivi_room/test/features/auth/providers/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vivi_room/core/services/api_client.dart' as _i3;
import 'package:vivi_room/core/services/token_storage_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTokenStorageService_0 extends _i1.SmartFake
    implements _i2.TokenStorageService {
  _FakeTokenStorageService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i3.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TokenStorageService get tokenStorage =>
      (super.noSuchMethod(
            Invocation.getter(#tokenStorage),
            returnValue: _FakeTokenStorageService_0(
              this,
              Invocation.getter(#tokenStorage),
            ),
          )
          as _i2.TokenStorageService);

  @override
  set onUnauthorized(_i4.Future<void> Function()? value) => super.noSuchMethod(
    Invocation.setter(#onUnauthorized, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<Map<String, dynamic>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getMe() =>
      (super.noSuchMethod(
            Invocation.method(#getMe, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getClientas({String? query}) =>
      (super.noSuchMethod(
            Invocation.method(#getClientas, [], {#query: query}),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getServicios() =>
      (super.noSuchMethod(
            Invocation.method(#getServicios, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getCitas() =>
      (super.noSuchMethod(
            Invocation.method(#getCitas, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getCitasDia(String? fecha) =>
      (super.noSuchMethod(
            Invocation.method(#getCitasDia, [fecha]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getCitasSemana(String? inicio) =>
      (super.noSuchMethod(
            Invocation.method(#getCitasSemana, [inicio]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> crearCita({
    required String? idServicio,
    required String? fechaHora,
    required int? duracion,
    String? idClienta,
    double? montoAnticipo,
    String? notas,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crearCita, [], {
              #idServicio: idServicio,
              #fechaHora: fechaHora,
              #duracion: duracion,
              #idClienta: idClienta,
              #montoAnticipo: montoAnticipo,
              #notas: notas,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getClientaDetalle(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getClientaDetalle, [id]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getClientaHistorial(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getClientaHistorial, [id]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> updateClienta(
    String? id, {
    required String? nombre,
    required String? telefono,
    String? alergias,
    String? preferencias,
    String? notas,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateClienta,
              [id],
              {
                #nombre: nombre,
                #telefono: telefono,
                #alergias: alergias,
                #preferencias: preferencias,
                #notas: notas,
              },
            ),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> eliminarClienta(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#eliminarClienta, [id]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> changePassword({
    required String? passwordActual,
    required String? passwordNueva,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #passwordActual: passwordActual,
              #passwordNueva: passwordNueva,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getServiciosInactivos() =>
      (super.noSuchMethod(
            Invocation.method(#getServiciosInactivos, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getCitaDetalle(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCitaDetalle, [id]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> editarCita(
    String? id,
    Map<String, dynamic>? campos,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editarCita, [id, campos]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> createClienta({
    required String? nombre,
    required String? telefono,
    String? alergias,
    String? preferencias,
    String? notas,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createClienta, [], {
              #nombre: nombre,
              #telefono: telefono,
              #alergias: alergias,
              #preferencias: preferencias,
              #notas: notas,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> crearServicio({
    required String? nombre,
    required String? descripcion,
    required double? precio,
    required int? duracionMin,
    required int? activo,
    required int? proximamente,
    required int? esCombo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crearServicio, [], {
              #nombre: nombre,
              #descripcion: descripcion,
              #precio: precio,
              #duracionMin: duracionMin,
              #activo: activo,
              #proximamente: proximamente,
              #esCombo: esCombo,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> actualizarServicio(
    String? id, {
    required String? nombre,
    required String? descripcion,
    required double? precio,
    required int? duracionMin,
    required int? activo,
    required int? proximamente,
    required int? esCombo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #actualizarServicio,
              [id],
              {
                #nombre: nombre,
                #descripcion: descripcion,
                #precio: precio,
                #duracionMin: duracionMin,
                #activo: activo,
                #proximamente: proximamente,
                #esCombo: esCombo,
              },
            ),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [TokenStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStorageService extends _i1.Mock
    implements _i2.TokenStorageService {
  MockTokenStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> readToken() =>
      (super.noSuchMethod(
            Invocation.method(#readToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> clearToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveUser(String? userJson) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [userJson]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> readUser() =>
      (super.noSuchMethod(
            Invocation.method(#readUser, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> clearUser() =>
      (super.noSuchMethod(
            Invocation.method(#clearUser, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
